language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
