[package]
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
name = "meval"
description = "A simple math expression parser and evaluator."
version = "0.0.1"
license = "MIT"
keywords = ["math", "parser", "expression", "formula", "evaluator"]

[dependencies]

[dependencies.nom]
git = "https://github.com/Geal/nom.git"

[dev-dependencies]
gnuplot = "0.0.18"
