[package]
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
name = "math_eval"
version = "0.0.1"

[dependencies]

[dependencies.nom]
git = "https://github.com/Geal/nom.git"

[dev-dependencies]
gnuplot = "0.0.18"
