[package]
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
description = "A simple math expression parser and evaluator."
documentation = "http://rekka.github.io/meval-rs/meval/index.html"
homepage = "https://github.com/rekka/meval-rs"
keywords = ["math", "parser", "expression", "formula", "evaluator"]
license = "Unlicense/MIT"
name = "meval"
readme = "README.md"
repository = "https://github.com/rekka/meval-rs"
version = "0.0.6"

[dependencies]
fnv = "1.0.5"
nom = "1.0.0"

[dev-dependencies]
gnuplot = "0.0.18"
